import React, { Component } from "react";
import "./sustainable-shopping.css";
import { Container, Row, Col, Image } from "react-bootstrap";

export default class SustainableShopping extends Component {
  render() {
    return (
      <Container className="wide-row-container sustainable-shopping-row">
        <Row>
          <Col className="sustainable-shopping-image-col" xs={12} md={6}>
            <Image
              className="sustainable-shopping-image"
              src="/assets/img/shop.png"
              fluid
            />
          </Col>
          <Col className="sustainable-shopping-text-col" xs={12} md={6}>
            <div>
              <h2 className="roboto-font fw-600 sustainable-shopping-header">
                {" "}
                SUSTAINABLE SHOPPING{" "}
              </h2>
              <p>
                Fast-fashion is overtaking the industry, producing clothes more
                efficiently than ever before, but at the cost of the
                environment. To produce one cotton shirt, it takes the amount of
                water that the average person drinks in two and a half years.
                The clothing waste generated by fast-fashion can also sit around
                for up to 200 years.
              </p>
              <p>
                On the SocialMirror network, you can directly help combat this
                by listing your used clothing for sale. Selling used clothes to
                others is an effective way of reducing the amount of new clothes
                purchased, reusing old items, and not creating more waste.
              </p>
            </div>
          </Col>
        </Row>
      </Container>
    );
  }
}
